export const userLoginActions = {
        USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
        USER_LOGIN_FAILURE : "USER_LOGIN_FAILURE",
        RESET_LOGIN : "RESET_LOGIN"
}

export const userRegisterActions = {
    USER_SIGNUP_SUCCESS : "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_FAILURE : "USER_SIGNUP_FAILURE",
    RESET_SIGNUP : "RESET_SIGNUP"
    
}